### ISSUE TITLE
Backend/Veranstalter - nur neu hinzugefügte in Liste

### ISSUE THREAD

**Issue by gabbagnom** [Scarysize/alternativfeiern_app#1]
-im Backend bei Veranstalter sieht man nur neu hinzugefügte in der Liste unten
-bereits existierende erscheinen nicht

**Comment by Scarysize** [comment]
Die existierenden sind momentan noch hard codiert. Müssen alle neu angelegt werden.

**Comment by Scarysize** [comment]
Habe die existierenden übertragen.
