### ISSUE TITLE
 [feature] vergangene events 

### ISSUE THREAD

**Issue by gabbagnom** [Scarysize/alternativfeiern_app#12]
- eine Anzeige/Liste für vergange Events wäre noch gut (ganz kleiner button auf der hauptseite, oder unten im footer irgendwo

**Comment by Scarysize** [comment]
@gabbagnom reicht ein Link mit "Archiv" der einfach eine lange Liste mit Links zu den vergangen Events ist?

**Comment by gabbagnom** [comment]
japp, wenns geht aber mit datum vorne
