### ISSUE TITLE
Frontend/Veranstalter - neu hinzugefügte fehlen

### ISSUE THREAD

**Issue by gabbagnom** [Scarysize/alternativfeiern_app#2]
- neu hinzugefügte Veranstalter sieht man nicht im Frontend

**Comment by Scarysize** [comment]
Muss erst implementiert werden, damit die Veranstalter aus der DB abgerufen werden. Momentan noch hart codiert. Mache ich wenn alle bestehenden übertragen sind.

**Comment by Scarysize** [comment]
Werden jetzt aus der Datenbank geholt und angezeigt:
[http://alternativ-feiern.de/organizers](http://alternativ-feiern.de/organizers)
